version: 2
jobs:
  dev-publish-pipeline:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - checkout
      - run: aws stepfunctions start-execution --state-machine-arn  arn:aws:states:us-east-1:782123507683:stateMachine:blog-post-pipeline
  publish-pipeline:
      docker:
        - image: mesosphere/aws-cli
      steps:
        - checkout
        - run: aws stepfunctions start-execution --state-machine-arn  arn:aws:states:us-east-1:448673940787:stateMachine:blog-post-pipeline
workflows:
  version: 2
  deploy:
      dev:
        jobs:
          - dev-publish-pipeline:
              context: kickoff-blog-post-pipeline
              filters:
                branches:
                  only:
                    - master
      prod:
        jobs:
          - publish-pipeline:
              context: kickoff-blog-post-pipeline-prod
              filters:
                tags:
                  only:
                    - /publish:.*/